### PR TITLE
Make default project name lowercase

### LINKED ISSUE #378: docker-compose project name restrictions - can not set project name
**Setup:**

- `id "com.avast.gradle.docker-compose" version "0.16.9"`
- docker version: 20.10.18
- Docker Compose version v2.10.2

**Problem:**
It seems like newer versions of docker-compose somewhat restrict the project name (no uppercase characters), see https://github.com/docker/compose/issues/9741. Unfortunately, the project name generated by  the `gradle-docker-compose-plugin` for the following config

```
dockerCompose {
        isRequiredByIntegrationTest 'docker/docker-compose.yml'
    }
```
is `1bd882aa0fc45e9fb48ec8510af6c6d8_xxxxxx_integrationTest` (notice the uppercase "T")

Therefore when I run the integration tests I get the following error message:
`"1bd882aa0fc45e9fb48ec8510af6c6d8_xxxxxx_integrationTest" is not a valid project name.`

**Therefore, I would suggest this you to not generate project names with uppercase characters as a fix!**

Other than that I tried to set the project name manually, like

```
dockerCompose {
        projectName 'lowercase-only'
        isRequiredByIntegrationTest 'docker/docker-compose.yml'
    }
```

**However this seems to have no effect at all!** How can I set the project name correctly? Or why is it not working like that?

### PR DESCRIPTION
**Pull request by aykborstelmann**
Fixes #378

### CODE REVIEW

File: src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy [hunk 1]
```diff
@@ -89,7 +89,7 @@ abstract class ComposeSettings {
 
     @Inject
     ComposeSettings(Project project, String name = '', String parentName = '') {
-        this.nestedName = parentName + name
+        this.nestedName = (parentName + name).toLowerCase()
         this.safeProjectNamePrefix = generateSafeProjectNamePrefix(project)
```
Comment (augi) [inline src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy:93]: IMHO we should lowercase also this value 🤔 

The question then is if it were better to move the lowercasing to the `projectNameProvider` 🤔

**Review by augi — CHANGES_REQUESTED** [review]

File: src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy (hunk 1 above)
Comment (aykborstelmann) [reply src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy:93]: `generateSafeProjectNamePrefix` generates only lowercase value as far as I know. 

But I think it may actually be a good idea to just lowercase whatever the provider returns. That would also include to lowercase `customProjectName`

Comment (aykborstelmann) [reply src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy:93]: That could of course again be a problem from user view, because then `projectName` would differ to the input `projectName`

Comment (augi) [reply src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy:93]: Agree 👍

Comment (aykborstelmann) [reply src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy]: Okay how about 5b5df1ab20a1506fc5d3f82bac400f614053eee7

File: src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy [hunk 2]
```diff
@@ -101,7 +101,7 @@ abstract class ComposeSettings {
             else {
                 return "${safeProjectNamePrefix}_${nestedName}"
             }
-        })
+        }).map{ it.toLowerCase()}
```
Comment (augi) [inline src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy:104]: Could you please just drop a comment here, why are we lowercasing? 🙏

**Review by augi — CHANGES_REQUESTED** [review]

File: src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy (hunk 2 above)
Comment (aykborstelmann) [reply src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy]: Sure, done 273db55e314c83a2f385e41ec51f33db2e929b0f

**Comment by augi** [comment]
Thank you for your contribution! Will be released as `0.16.11`.
